### ISSUE TITLE
Update check causes a crash in Travis CI

### ISSUE THREAD

**Issue by SpaceK33z** [zeit/update-check#5]
I ran into a really weird error a couple of times with Travis CI, running on Node v8;

```
$ now -t ${NOW_TOKEN} -T volst --no-verify
> Error! An unexpected error occurred!
  Error: ENOENT: no such file or directory, open '/tmp/update-check/now-latest.json' Error: ENOENT: no such file or directory, open '/tmp/update-check/now-latest.json'
```

The app is open source, so you can find the Travis CI [logs here](https://travis-ci.org/Volst/foed/jobs/377871410#L494). What makes it difficult to debug though is that it doesn't happen *always*. And a link to the [travis.yml file](https://github.com/Volst/foed/blob/master/.travis.yml#L19-L20).

I don't know why this happens, but I guess `update-check` should gracefully handle that file not existing, even though it may be because there is some exotic config going in a CI, right?

**Comment by leo** [comment]
Hmmm, we could technically simply disable `update-check` in CI, but we want to keep showing messages for people who need to upgrade their locked Now CLI in CI...

Would you be open for checking whether this is failing with a very basic Travis config? Maybe yours is somehow making the /tmp directory unwritable or unreadable.

**Comment by SpaceK33z** [comment]
I don't think I can reproduce this with a basic Travis config, in the last 3 days this bug hasn't re-occured. Around the time it occured Travis was also acting weird with cached folders not being updated (discovered that later), so it might just have been a Travis bug.

Soo I'll close this for now and will keep an eye on of it re-occurs. Sorry 😅.
